## Tutorial
This tutorial aims to present how to obtain vector representation of a graph using anonymous walks. In this tutorial we will show: 
* How to obtain anonymous walk distribution of a graph. 
* How to compute graph kernel from embeddings of graphs. 
* How to evaluate performance of kernel matrix in graph classification task. 

Dependencies: 
* networkx (v. 1.11+)
* tensorflow (v. 1.4.0+)
* scikit-learn (v. 0.18.1+)

### Reading graphs

`read_graphs` function allows to read graphs as networkx Digraph object. The input can be any of the 2 options: 
1. Folder, where graphs are located and their file extensions.
2. List of all filenames. 

In the first case, graph filenames should have an index (e.g. graph1.graphml or mutag_20.graphml). This index will be automatically used by the classifier to link it with graph class. 

In [1]:
from AnonymousWalkKernel import GraphKernel

gk = GraphKernel()
gk.read_graphs(folder = './Datasets/mutag/', ext = 'graphml')

print('Number of graphs: {}'.format(len(gk.graphs)))

Number of graphs: 188


### Getting feature-based embedding of a graph
`AnonymousWalks` class contains functions to calculate distribution of anonymous walks in a graph. 

In [17]:
from AnonymousWalkKernel import AnonymousWalks

G = gk.graphs[0]
aw = AnonymousWalks(G)
length = 3 # length of anonymous walks

aw._all_paths(steps=length)
print('All possible anonymous walks of length up to {} (a.k.a embedding size)'.format(length))
print(aw.paths[length])

All possible anonymous walks of length up to 3 (a.k.a embedding size)
[[0, 1, 0], [0, 1, 2], [0, 1, 2, 0], [0, 1, 0, 1], [0, 1, 2, 1], [0, 1, 0, 2], [0, 1, 2, 3]]


We can get _exact_ distribution of anonymous walks in a graph for small lengths (e.g. $l <= 7$) using `embed` method.

In [3]:
import time

length = 4
start = time.time()
embedding, meta = aw.embed(steps = length, method = 'exact', keep_last=True, verbose=False)
finish = time.time()

aws = meta['meta-paths']
print('Computed Embedding of {} dimension in {:.3f} sec.'.format(len(aws), finish - start))
print()
print('Embedding:')
print(embedding)
print()
print('Anonymous Walks of length {}:'.format(length))
print(aws)

Computed Embedding of 15 dimension in 0.021 sec.

Embedding:
[0.08742619431025227, 0.09923510466988726, 0.09923510466988733, 0, 0, 0, 0, 0, 0.10782340311325822, 0.09923510466988726, 0.13560118089103612, 0, 0.0539452495974235, 0.12822061191626416, 0.18927804616210467]

Anonymous Walks of length 4:
[[0, 1, 0, 1, 0], [0, 1, 2, 1, 0], [0, 1, 0, 2, 0], [0, 1, 2, 3, 0], [0, 1, 2, 0, 1], [0, 1, 0, 2, 1], [0, 1, 2, 3, 1], [0, 1, 2, 0, 2], [0, 1, 0, 1, 2], [0, 1, 2, 1, 2], [0, 1, 2, 3, 2], [0, 1, 2, 0, 3], [0, 1, 2, 1, 3], [0, 1, 0, 2, 3], [0, 1, 2, 3, 4]]


We can also use _sampling_ approach to get distribution. There are two ways to control the number of samples:
1. $\varepsilon$ and $\delta$ to control $\varepsilon$-proximity to the true anonymous walk  distribution,
2. Monte-Carlo simulations MC. 

In [4]:
length = 10
start = time.time()
embedding, meta = aw.embed(steps = length, method = 'sampling', keep_last=True, verbose=False, MC=100)
finish = time.time()


aws = meta['meta-paths']
print('Computed Embedding of {} dimension in {:.3f} sec.'.format(len(aws), finish - start))

Computed Embedding of 115975 dimension in 0.296 sec.

Embedding:
[0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

### Getting feature-based embeddings of all graphs

We can embed all graphs using `GraphKernel` class.

In [5]:
length = 3
gk.embed_graphs(steps = length, keep_last=True)

E = gk.embeddings
print('Embeddings matrix of shape: {} x {}'.format(E.shape[0], E.shape[1]))
print(E[:10, :])

Using exact method to get graph embeddings
Dimension size: 5
Processing 0 graph
Processing 10 graph
Processing 20 graph
Processing 30 graph
Processing 40 graph
Processing 50 graph
Processing 60 graph
Processing 70 graph
Processing 80 graph
Processing 90 graph
Processing 100 graph
Processing 110 graph
Processing 120 graph
Processing 130 graph
Processing 140 graph
Processing 150 graph
Processing 160 graph
Processing 170 graph
Processing 180 graph
Embeddings matrix of shape: 188 x 5
[[0.         0.1952496  0.25241546 0.22745572 0.32487923]
 [0.         0.22792023 0.3005698  0.1994302  0.27207977]
 [0.         0.19590643 0.26169591 0.2251462  0.31725146]
 [0.         0.1952496  0.25322061 0.22745572 0.32407407]
 [0.         0.21132898 0.26252723 0.22657952 0.29956427]
 [0.         0.20185185 0.26342593 0.22037037 0.31435185]
 [0.         0.2137037  0.28444444 0.21074074 0.29111111]
 [0.         0.20077973 0.25584795 0.22612086 0.31725146]
 [0.         0.19477513 0.26190476 0.21990741 0.323

### Getting kernel matrix from embeddings
Once you have a matrix of graph embeddings (or any feature matrix) you can compute kernel matrix from it. There are 3 types of kernels:
1. RBF (a.k.a. gaussian): $\exp (\dfrac{\Vert x - y\Vert^2}{2\sigma^2})$
2. Polynomial: $(xy + c)^d$
3. Dot: $xy$

In [6]:
gk.embeddings = E
gk.kernel_matrix(kernel_method='rbf', build_embeddings=False)
K = gk.K
print('Kernel matrix has shape: {} x {}'.format(K.shape[0], K.shape[1]))
print(K[:10, :])

Kernel matrix has shape: 188 x 188
[[1.         0.99860908 0.99996999 ... 0.99930335 0.99938821 0.99945732]
 [0.99860908 1.         0.99895298 ... 0.99982104 0.99966848 0.99972676]
 [0.99996999 0.99895298 1.         ... 0.99951331 0.99956652 0.99964692]
 ...
 [0.99997953 0.9989027  0.99998822 ... 0.99951962 0.99959059 0.99964528]
 [0.99997012 0.99887104 0.99998665 ... 0.99942533 0.99945418 0.99955218]
 [0.99969689 0.99959094 0.99984945 ... 0.99987741 0.99986328 0.99993335]]


### Evaluating performance
To evaluate performance of kernel matrix we need to read graph classes and use `Evaluation` class. It runs SVM algorithm and performs k-fold cross-validation on train-val-test splits. 

In [7]:
import numpy as np
# reading classes of graphs
y = []
with open('Datasets/mutag/labels.txt') as f:
    for line in f:
        y.extend(list(map(int, line.strip().split())))
y = np.array(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [8]:
from AnonymousWalkKernel import Evaluation
k = 10
ev = Evaluation(matrix = K, labels = y, verbose = False)
accuracies = ev.evaluate(k=k)
print('Performed {}-fold validation and scored {:.2f}% mean accuracy in graph classification'.format(k, 100*np.mean(accuracies)))

Performed 10-fold validation and scored 66.37% mean accuracy in graph classification


### Getting distributed Anonymous Walk Embeddings (AWE)

Distributed model has a variety of parameters. The inputs are: 
* dataset: name of the dataset and corresponding name of the folder.
* batch_size: number of batches per iteration of AWE model.
* window_size: number of context words.
* concat: Concatenate context words or not.
* embedding_size_w: embedding size of word
* embedding_size_d: embedding size of document
* loss_type: sampled softmax or nce
* num_samples: number of (negative) samples for every target word.
* optimize: SGD or Adagrad
* learning_rate: learning rate of the model
* root: root folder of the dataset
* ext: extension of files with graphs (e.g. graphml)
* steps: length of anonymous walk
* epochs: number of epochs for iterations
* batches_per_epoch: number of batches per epoch for each graph
* candidate_func: None (loguniform by default) or uniform
* graph_labels: None, edges, nodes, edges_nodes

In [15]:
from AnonymousWalkEmbeddings import AWE

dataset = 'mutag'

batch_size = 100
window_size = 8
embedding_size_w = 128
embedding_size_d = 128
num_samples = 32

concat = False
loss_type = 'sampled_softmax'
optimize = 'Adagrad'
learning_rate = 1.0
root = 'Datasets/'
ext = 'graphml'
steps = 7
epochs = 1
batches_per_epoch = 50
candidate_func = None
graph_labels = y

In [16]:
awe = AWE(dataset = dataset, batch_size = batch_size, window_size = window_size,
                  embedding_size_w = embedding_size_w, embedding_size_d = embedding_size_d,
                  num_samples = num_samples, concat = concat, loss_type = loss_type,
                  optimize = optimize, learning_rate = learning_rate, root = root,
                  ext = ext, steps = steps, epochs = epochs, batches_per_epoch = batches_per_epoch,
                  candidate_func = candidate_func, graph_labels=graph_labels)

Number of graphs: 188
Generating corpus... 

/home/gear/Gdrive/Projects/reference/AWE/AnonymousWalkEmbeddings.py:136: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.graph_labels == 'nodes':
/home/gear/Gdrive/Projects/reference/AWE/AnonymousWalkEmbeddings.py:138: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.graph_labels == 'edges':
/home/gear/Gdrive/Projects/reference/AWE/AnonymousWalkEmbeddings.py:140: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  elif self.graph_labels == 'edges_nodes':


KeyError: 7

In [ ]:
print()
start2emb = time.time()
awe.train() # get embeddings
finish2emb = time.time()
print()
print('Time to compute embeddings: {:.2f} sec'.format(finish2emb - start2emb))

In [ ]:
E = awe.graph_embeddings
print('Shape of embedding matrix: {}'.format(E.shape))
gk.embeddings = E
gk.kernel_matrix(build_embeddings=False, kernel_method='poly', d = 3, c = 1)
K = gk.K
print('Shape of kernel matrix: {}'.format(K.shape))
print()
print(K[:10, :])

### Getting kernel matrix from embeddings
If you have an embedding matrix `E` obtained by any model, you can compute a kernel matrix using `GraphKernel` class. The choice for kernel function is among `rbf`, `poly`, and `dot`. 

To provide access to embeddings matrix, you have 2 choices. 

In [ ]:
from AnonymousWalkKernel import GraphKernel

gk = GraphKernel()

# Option 1. Load embeddings from graph kernel method.  
E = gk.load_embeddings('mutag_embeddings.txt.npz')
print('Option 1')
print(E[:2, :2])

# Option 2. Assign the matrix. 
random_matrix = np.random.random((10,20))
gk.embeddings = random_matrix
E = gk.embeddings
print('Option 2')
print(E[:2, :2])

In [ ]:
# RBF kernel with sigma = 0.5
# build_embeddings = False reuses embeddings already provided to the class
gk.kernel_matrix(kernel_method = 'rbf', build_embeddings=False, sigma=0.5)
K = gk.K
print('RBF:')
print(K)

In [ ]:
# Poly kernel with c = 1 and d = 3
gk.kernel_matrix(kernel_method = 'poly', build_embeddings=False, c = 1, d = 3)
K = gk.K
print('Poly:')
print(K)

### Repro